services:
  db:
    image: postgres:14
    container_name: alvesbank_db
    environment:
      POSTGRES_DB: AlvesBank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
